### ISSUE TITLE
Town boundary width and height are swapped

### ISSUE THREAD

**Issue by daerogami** [calref/cboe#101] opened 2018-02-15 08:36 UTC
Towns that do not have their boundaries drawn in a square have redrawn themselves
e.g. if it is 28x30, it becomes 30x28, and moves the party out of town when it shouldn't.

---
This is an item logged from the To-Do and was originally reported by BainIhrno. If you are familiar with or can recreate this bug, please provide details here.

**Comment by NQNStudios** [comment] 2024-09-08 00:03
@CelticMinstrel did you merge the fix for this?

**Comment by CelticMinstrel** [comment] 2024-09-08 00:21
Looks like I didn't. I think it was probably because it looked messy and I didn't have time to comb through it and double-check it's all correct.

**Comment by NQNStudios** [comment] 2024-09-08 01:16
Could be a good candidate for a test scenario. I wonder if the current build of the scenario editor on windows will reproduce the bug, or if it has to be a legacy windows scenario.

**Comment by CelticMinstrel** [comment] 2024-09-08 02:57
The commit that fosnola posted is clearly addressing a possible legacy conversion issue. I don't know for sure if the original issue from my TODO list was about legacy conversion.

**Comment by fosnola** [comment] 2024-09-08 10:16
This is very old. I think the problem was that the old codes used native rectangle structures on Windows (RECT) and Mac ( Rect ), probably also point structures. This meant that if you had to switch from one format to the other, you had to both convert these structures and change the endian mode.
As in the new code, there is now only one structure for rectangles, the conversion is a little different. Rectangles have to be converted if the original stored the members in a different order. Integers must also be converted, changing the endian mode if necessary. Ie. The two are no longer necessarily strongly coupled.

**Note:** I can't remember the name of the game, but I think I discovered this problem in a game with a circus and gypsies. Before the fix, you'd sometimes leave a town unintentionally (as squares were not used to define town boundaries), I also remember finding myself in the middle of a lake...

**Comment by CelticMinstrel** [comment] 2024-09-08 15:15
> probably also point structures.

No, only the rectangle native structure was used. The main problem here is that the two types are _completely incompatible_ – aside from endian issues, the Mac rectangle used a `top, left, bottom, right` format, whereas the Windows rectangle used a `x1, y1, x2, y2` format. Since I was working off the Mac source, my conversion port uses the former format (because it meant literal rectangles in the source code didn't need any adjustments).

If I recall correctly, the original Blades of Exile does not run on Intel Macs, so it's safe to assume that all Mac scenarios are also big-endian. So, in a Mac scenario, we just need to flip endian like normal… but in a Windows scenario, we _don't_ flip endian, but we _do_ swap the first two coordinates and the second two coordinates.

All the code to do that properly is already in place. From what I can tell of fosnola's commit, it seems there may just be some places we forgot to call it? Or there are some places where we call it when we shouldn't.

I think the code currently makes the assumption that it's running on a little-endian machine, which it probably shouldn't, but making it not probably isn't a priority (who even uses a big-endian machine these days? maybe some niche Linux users?).

**Comment by NQNStudios** [comment] 2024-09-08 15:19
I’m open to making some test scenarios, legacy and new format, with a
rectangular town, to reproduce the bug and check if the commits fix it.

**Comment by NQNStudios** [comment] 2024-09-08 15:29
I can probably make legacy Windows scenarios because i have that emulation
set up. Can’t do legacy mac scenarios though.

**Comment by fosnola** [comment] 2024-09-08 15:52
I'm not sure, but when I mentioned problems in a game, I might have been thinking of A Band of Wanderers (http://www.spiderwebsoftware.com/blades/scen_stuff/solid.html). In any case, I remember a lot of problems with this scenario when I first played it.

**Comment by CelticMinstrel** [comment] 2024-09-08 19:17
I can theoretically make legacy Mac scenarios, but I can't do it right at this moment. Need to set up my old Mac first, where I have a working Basilisk II emulation set up, _or_ somehow figure out a way to set up Basilisk II on my new Mac. Basilisk II is really hard to set up though, so the former is more likely to happen. (I think I actually may have downloaded a pre-built, working setup from somewhere… which is probably not something I'd be able to find again.)

Saving a formerly Mac scenario with the Windows editor _does_ turn it into a Windows scenario, right? (If it didn't, you might be able to make Mac scenarios by editing an existing one.)

---

I want to add two more things.

1. I'm not _completely_confident that the original post was, in fact, a legacy conversion error. That said, given that it seemingly came from somewhere else, it is _likely_ to be.
2. If it _is_ a legacy conversion issue, it's quite likely to be something that occurred in a scenario created by forum user Bain-Ihrno, given that the original report came from them.

I do have an old save file sent to me by Bain-Ihrno. I suspect it's not related to this issue though, as it looks like an outdoors save file.

**Comment by NQNStudios** [comment] 2024-09-08 22:24
Now I can't remember how to launch the windows emulation haha. I think it was console commands, not a trivial thing. Sheesh

**Comment by fosnola** [comment] 2024-09-09 11:08
I've just created a small scenario with version 1.0.4 of Blades of Exile Scenario Editor (in case it's of any use). 

**Note**: I couldn't find an Export menu ( just a Save menu ). I'm not sure my town is well built either, start is probably outside its boundaries.

[mac.exs.zip](https://github.com/user-attachments/files/16929462/mac.exs.zip)
<img width="577" alt="Capture d’écran 2024-09-09 à 13 00 19" src="https://github.com/user-attachments/assets/e22f9d9d-0770-4e86-b110-83b5f6048d4a">
<img width="582" alt="Capture d’écran 2024-09-09 à 12 56 11" src="https://github.com/user-attachments/assets/3e9718ee-9074-44c9-8907-1c2c052bcbc9">

**Comment by NQNStudios** [comment] 2024-09-09 19:43
I've reproduced the bug by running this scenario I created in Windows 98 emulation: 
[recttown.zip](https://github.com/user-attachments/files/16935690/recttown.zip)

![image](https://github.com/user-attachments/assets/f9c24658-4a65-4ace-99c5-0cd6d7ec1c84)

**Comment by NQNStudios** [comment] 2024-09-09 19:49
And the same scenario created with the latest OBoE scenario editor on Windows works as expected.

**Comment by NQNStudios** [comment] 2024-09-09 19:52
@fosnola if it's not too much trouble could you open your legacy Mac scenario again and edit it to match the one I've created and re-upload? No walls, just brick floor marking where the boundary is, and the start location needs to be inside the boundary.

**Comment by fosnola** [comment] 2024-09-10 08:36
here is the new file
[townrectMac.exs.zip](https://github.com/user-attachments/files/16941937/townrectMac.exs.zip)

**Note** I'll try a little later to recover the windows file, reopen it in the old editor and then resave it, to check that the conversion goes well (that is, if my version is capable of opening windows files).

**Comment by fosnola** [comment] 2024-09-10 08:51
Oops, this version must be better, ie. with floor instead of wall 
[townrectMac.exs.zip](https://github.com/user-attachments/files/16942146/townrectMac.exs.zip)

**Comment by fosnola** [comment] 2024-09-10 10:02
Last, the Windows scenario, I reopened it on a Mac and then I just saved it:
[recttownWinToMac.exs.zip](https://github.com/user-attachments/files/16943034/recttownWinToMac.exs.zip)

**Comment by NQNStudios** [comment] 2024-09-10 14:37
@celticminstrel so the newer .boes scenarios are tar archives? What command
do I use to unpack one before committing it? And how would a unit test load
an unpacked boes folder?

**Comment by CelticMinstrel** [comment] 2024-09-10 18:20
> What command do I use to unpack one before committing it?

Look at pkg/unpack_scenario.sh.

> And how would a unit test load an unpacked boes folder?

When calling `load_scenario` you have the option of passing either a .boes file or a .exs file. Since every .boes file contains a header.exs file inside it, you can use that to load an unpacked scenario (Note: the header.exs file is _not_ a valid legacy scenario, just for the record.)

**Comment by NQNStudios** [comment] 2024-11-26 19:59
Was closed by #441

**Closed by NQNStudios** 2024-11-26 19:59 UTC
Labels: bug, game
