### ISSUE TITLE
Display Picture doesn't work

### ISSUE THREAD

**Issue by daerogami** [calref/cboe#131] opened 2018-02-15 09:05 UTC
Gives an error about accessing a message out of range.

---
This is an item logged from the To-Do and was originally reported by Tados. If you are familiar with or can recreate this bug, please provide details here.

**Comment by NQNStudios** [comment] 2024-08-07 19:02
Can't reproduce on MacOS

**Comment by NQNStudios** [comment] 2024-08-07 20:23
Can't reproduce on Windows

**Comment by NQNStudios** [comment] 2024-08-07 20:49
Can't reproduce on Linux.

@CelticMinstrel Can we close this?

**Comment by NQNStudios** [comment] 2024-08-07 20:50
To try to reproduce, I made a new scenario with a Display Picture node and a custom graphic for it. For each platform, I launched the scenario and triggered the node to see that it worked.

**Comment by CelticMinstrel** [comment] 2024-08-08 05:53
I'm not sure if this is related, but there exists _one_ semi-legacy scenario that uses a Display Picture node (semi-legacy because it predates the new scenario format but is not vanilla BoE). I'm _pretty_ sure it's Pilgrimage to Thrakos. It might be worth testing whether the Display Picture node works in that scenario as well. If it fails in a different way than described here though, it should be opened as a separate bug (a legacy porting bug, technically) and this one should probably be closed.

**Comment by NQNStudios** [comment] 2024-08-08 20:25
Just tried launching Pilgrimage to Thrakos and there's this warning:

<img width="320" alt="Screenshot 2024-08-08 at 3 23 50 PM" src="https://github.com/user-attachments/assets/0ffc5ba3-c458-40f1-ab82-6598bc955e42">

I wonder why the format can't be converted?

And are there any vanilla BoE scenarios that use Display Picture that we need to worry about?

**Comment by CelticMinstrel** [comment] 2024-08-09 06:03
Ahh, so I decided not to bother converting it…?

Automatic conversion is _probably_ possible but very difficult. I believe the Display Picture node specifies a path to an external file, so I think it could theoretically be converted by effectively copying said file into the scenario package… though this is more of a conversion for the scenario editor rather than something easily done at runtime in the game.

> And are there any vanilla BoE scenarios that use Display Picture that we need to worry about?

To my knowledge, Pilgrimage to Thrakos is the only scenario (at least, the only one of any significance) that uses this feature. Perhaps that also played into my choice to not bother converting it – if it's only one scenario, it's easier to fix the scenario.

The Display Picture node does not exist in true vanilla BoE – it was one of several new features added during development on the Windows branch of the game. When I merged that work in with the Mac branch, I chose to redo the Display Picture in an incompatible way (probably to maintain the integrity of the scenario package or something) and this is the result.

**Closed by CelticMinstrel** 2024-08-09 06:03 UTC
Labels: bug, game
