### ISSUE TITLE
The "if in boat" call causes the special node not to happen altogether, whether in a boat or not. 

### ISSUE THREAD

**Issue by daerogami** [calref/cboe#103] opened 2018-02-15 08:38 UTC
---
This is an item logged from the To-Do and was originally reported by BainIhrno. If you are familiar with or can recreate this bug, please provide details here.

**Comment by CelticMinstrel** [comment] 2020-02-10 05:32
Duplicate of #10 but implies that it's not entirely fixed, contrary to the comment there.

**Closed by CelticMinstrel** 2020-02-10 05:32 UTC
Labels: bug, game
