### ISSUE TITLE
Speed icon shown in party window when speed is not in any abnormal state

### ISSUE THREAD

**Issue by x-qq** [calref/cboe#230] opened 2020-01-17 03:00 UTC
As seen on an unrelated screenshot at https://0x0.st/zh0V.png

Original Exile 3 and Blades of Exile did not show the icon when there was no haste/slowness applied.

I personally find those icons distracting/disorienting (icons in party window usually meant some abnormal state that needs attention).

Could be made into a setting maybe?

**Comment by CelticMinstrel** [comment] 2020-01-22 04:07
Marking as a bug because original BoE didn't use this icon either on Mac or Windows (though Exile II did use it).

**Comment by NQNStudios** [comment] 2024-08-28 19:26
@CelticMinstrel I don't understand... couldn't you have made this refactor without introducing a regression and re-opening an issue?

I really don't want the normal speed icon to exist. I could introduce a preference to enable/disable it, but I think the default should be that it be off. I don't think anyone wants a normal speed icon.

**Comment by CelticMinstrel** [comment] 2024-08-28 20:01
The previous fix was incomplete, so I probably would've reopened it even if I hadn't done the refactor. I already have a commit to remove it again but I haven't pushed it because CI somehow broke.

**Comment by NQNStudios** [comment] 2024-08-28 20:03
Okay, thanks for clarifying. 🙏

**Comment by NQNStudios** [comment] 2024-08-28 20:29
I have reproduced the linux compiler error. I thought at first it was because of a const mismatch but that wasn't the case.

**Comment by NQNStudios** [comment] 2024-08-28 20:30
Actually it might be a const error.

**Comment by CelticMinstrel** [comment] 2024-08-28 20:31
That was my guess too, but when I looked at the code I couldn't see anything wrong, and it didn't happen on Mac, so I was stumped.

**Comment by NQNStudios** [comment] 2024-08-28 20:33
I added a const in a different place and it recompiled everything which I thought was a good sign but then came out with the same error

**Comment by CelticMinstrel** [comment] 2024-08-28 20:38
My other guess was that the new file is somehow not compiled on Linux, but that can't be right, can it? I dutifully added it to the SConscript, after all.

**Comment by NQNStudios** [comment] 2024-08-28 20:42
It is getting compiled, but maybe not by one of the 2 editors?

**Comment by NQNStudios** [comment] 2024-08-28 20:50
living.cpp, which the error is coming from, is compiled in this group:

`party_classes = Glob("#src/universe/*.cpp")`

damage.cpp is compiled in this group
`tools = SConscript("build/obj/tools/SConscript")`

**Comment by NQNStudios** [comment] 2024-08-28 20:53
but tools end up in `common_sources`....

**Comment by CelticMinstrel** [comment] 2024-08-28 21:05
And so do `party_classes`…

**Comment by NQNStudios** [comment] 2024-08-28 21:09
`scons game=true` works fine. `scons pcedit=true` fails.

**Comment by NQNStudios** [comment] 2024-08-28 21:11
I don't want to think about why it works now but I fixed it.

**Comment by NQNStudios** [comment] 2024-08-28 21:14
#419

**Closed** 2024-09-11 02:19 UTC
Labels: bug, game
