### ISSUE TITLE
Lightmask in Fungal Cavern (with Long Light) is shifted to the left.

### ISSUE THREAD

**Issue by clort81** [calref/cboe#219] opened 2020-01-05 20:07 UTC
Lightmask in Fungal Cavern (with Long Light) is shifted to the left.
![lightmaskerror](https://user-images.githubusercontent.com/51511737/71785405-6cfe6a00-2fff-11ea-9ebc-b97749f53640.png)

**Comment by wrldwzrd89** [comment] 2020-01-05 20:16
This looks like a positioning bug, perhaps related to whatever's causing #218 and #217, due to the party stats pane being an unexpected size.

**Comment by CelticMinstrel** [comment] 2020-01-22 04:02
Is this only with UIScale=2 or is it always?

**Comment by clort81** [comment] 2020-02-09 12:31
![shaderoffset](https://user-images.githubusercontent.com/51511737/74102076-79b33800-4b40-11ea-8d10-7d57137de05f.png)

I haven't tested with 1x scale yet.  Is this only seen by me?

**Comment by CelticMinstrel** [comment] 2023-01-06 05:37
Note that #218 was closed as a duplicate of #97.

**Comment by NQNStudios** [comment] 2024-12-01 14:27
#493 was a duplicate of this one, and is fixed. :)

**Closed by NQNStudios** 2024-12-01 14:27 UTC
Labels: bug, game
