### ISSUE TITLE
Outdoor wandering monsters are invisible

### ISSUE THREAD

**Issue by daerogami** [calref/cboe#125] opened 2018-02-15 09:00 UTC
---
This is an item logged from the To-Do and was originally reported by Tados. If you are familiar with or can recreate this bug, please provide details here.

**Comment by CelticMinstrel** [comment] 2018-02-16 03:14
I think this might've been fixed? Not sure.

**Comment by CelticMinstrel** [comment] 2020-02-10 05:33
Might be a duplicate of #237

**Comment by CelticMinstrel** [comment] 2023-01-06 05:55
It does look like it might be, but I can't be certain, mainly because this one is too sparsely described.

But then again, there isn't really a point in having an issue open if we don't even know what the issue is, so I guess I'll close it.

**Closed by CelticMinstrel** 2023-01-06 05:55 UTC
Labels: bug, duplicate, game
