### ISSUE TITLE
Possibly erroneous message out of range error

### ISSUE THREAD

**Issue by daerogami** [calref/cboe#77] opened 2018-02-15 08:01 UTC
Left fort terrace got "error, this message accessed a field out of range"

when I closed that the usual description of the vale popped up anyway...

---

This is an item logged from the To-Do and was originally reported by GiantFriendlyTalkingSpiderman. If you are familiar with or can recreate this bug, please provide details here.

**Comment by CelticMinstrel** [comment] 2018-02-18 22:04
This might be promoted to a general game issue, but for now I'm labelling it as a scenario issue since that's how it was reported.

I've also reproduced this error, so it's definitely still present.

**Comment by clort81** [comment] 2019-12-29 23:17
I can recreate with current build (Dec 30, 2019) on linux / aarch64.

![outofrange](https://user-images.githubusercontent.com/51511737/71564019-b5ff6d00-2a99-11ea-939d-2c42682028a0.png)

Maybe dialogues could be forked as well.  I'll see what i can do.

**Comment by clort81** [comment] 2020-01-04 04:29
I got a new message when passing the sign!  Cannot reliably recreate it.  What does it mean?
![textshift](https://user-images.githubusercontent.com/51511737/71759810-21d74080-2eb3-11ea-8051-1633d65f4aa2.png)

**Comment by CelticMinstrel** [comment] 2020-01-04 05:54
That's one of the debug modes. I guess it triggers an instant help message the first time it's used. If you have debug mode enabled (via Shift+D), you can toggle encounter step-through mode with Shift+1. (When debug mode is enabled you can also press / for debug help.)

Note that neither of these modes should ever be enabled when start a new scenario.

**Comment by clort81** [comment] 2020-01-04 11:07
Thanks for info CelticMinstrel:  Found a spot that triggers this also in Northwestern Vale (Near Marralis)
![messageoutofrange2](https://user-images.githubusercontent.com/51511737/71764649-b8732400-2eea-11ea-96cf-b0316d782e01.png)

**Comment by CelticMinstrel** [comment] 2020-01-04 15:43
I'm starting to suspect this might occur on any Dialog nodes that contain less than 6 strings.

(Note, "Dialog node" refers to the dialogs without a border around the text.)

**Comment by CelticMinstrel** [comment] 2020-01-13 00:10
This seems to have resulted from an early bug in the scenario format, resulting in incorrect scenario data. Commit e39ccf745b99348e5607342da1d30c347e8434c9 fixes this erroneous data in Valley of Dying Things, but the other scenarios still need to be checked for such cases.

To clarify, it occurs when:

1. A special node of any of the "Display Dialog" types (which also includes "Stairway" and a few others) is used which
2. References a string close to the end of the outdoors or town string list but
3. Without using a total of exactly six strings.

The fix is to ensure there are enough empty strings at the end of the list to satisfy the requirement of exactly 6 strings. It can be fixed in the scenario editor by editing the offending special, clicking the Create/Edit button next to the message, and clearing any strings that consist of just a `*`. Manually adding the required line to the XML would also work, of course, but with that method it's probably a little harder to verify which towns or outdoor sections need it.

**Comment by CelticMinstrel** [comment] 2020-02-10 05:46
Closing because I've since updated the scenarios as well to account for this issue.

**Closed by CelticMinstrel** 2020-02-10 05:46 UTC
Labels: VoDT, bug
