### ISSUE TITLE
Arrows don't poison (when using poison)

### ISSUE THREAD

**Issue by daerogami** [calref/cboe#105] opened 2018-02-15 08:40 UTC
---
This is an item logged from the To-Do and was originally reported by (@CelticMinstrel?). If you are familiar with or can recreate this bug, please provide details here.

**Comment by CelticMinstrel** [comment] 2020-02-10 05:21
This is a duplicate of #6 and may have been fixed already.

**Closed by CelticMinstrel** 2020-02-10 05:21 UTC
Labels: bug, game
