### ISSUE TITLE
Arrows fired by enemies (and player?) to offscreen targets draw outside game window.

### ISSUE THREAD

**Issue by clort81** [calref/cboe#218] opened 2020-01-05 15:41 UTC
Arrows fired by enemies (and player?) to offscreen targets draw outside game window.

I don't have a screencapture of the event but an archer fired an at a player that was off the current view, and the arrow continued animating past the game-world window.  

The 'damage' to the buttons at bottom got erased after arrow animation finished though.

**Comment by CelticMinstrel** [comment] 2020-01-06 13:57
I think I might've seen this awhile ago and the "damage" to the terrain frame was never fixed…?

Either way, failing to fix the "damage" isn't the issue here though. I probably just need to set a clipping rectangle (glScissor) or something.

**Comment by NQNStudios** [comment] 2023-01-06 05:34
I think this is a duplicate of #97

**Comment by CelticMinstrel** [comment] 2023-01-06 05:37
Yeah, looks like you're right.

**Closed by CelticMinstrel** 2023-01-06 05:37 UTC
Labels: bug, duplicate, game
