### ISSUE TITLE
Multiple Scenario Editor crashes

### ISSUE THREAD

**Issue by x-qq** [calref/cboe#244] opened 2020-01-27 05:42 UTC
* Scenario -> Advanced -> "Import Outdoor Sector" and then canceling file selection dialog
* Scenario -> Advanced -> "Set Scenario Event Timers" and press "ok" without doing anything

**Comment by NQNStudios** [comment] 2023-01-12 00:29
I'm guessing that the first crash in this list is fixed now along with #301

**Comment by NQNStudios** [comment] 2023-01-12 19:39
I reproduced the second crash on Windows. It came with an error message:

![imagen](https://user-images.githubusercontent.com/2584745/212164626-274b4235-01a6-48f6-b762-454b21f6db5d.png)

**Comment by NQNStudios** [comment] 2023-01-12 19:45
The crash also happens if you *do* set a scenario event timer.

**Comment by NQNStudios** [comment] 2023-01-12 20:03
It's happening here: https://github.com/calref/cboe/blob/master/src/scenedit/scen.core.cpp#L3145

`i + 1` is making it try to access time11, so I think it's an off-by-1 error.

**Comment by NQNStudios** [comment] 2023-01-12 20:14
That was wrong, sorry. It's here: https://github.com/calref/cboe/blob/master/src/scenedit/scen.core.cpp#L3109

Looks like the UI allows editing 10 when there are 20 (there's a TODO at the location of my last comment indicating this) but the save function is trying to disconnect UI events from 20 controls.

**Comment by NQNStudios** [comment] 2023-01-12 20:32
I think a stack widget could be added to hold 2 pages of fields for 10 events each.

**Comment by NQNStudios** [comment] 2023-01-12 21:52
> I'm guessing that the first crash in this list is fixed now along with #301

On this point I was also wrong. Windows and Linux both crash with an error message when you cancel the file browser to import outdoor sections AND import towns.

**Comment by NQNStudios** [comment] 2023-01-20 22:17
This issue can be closed now.

**Closed** 2023-01-21 00:17 UTC
Labels: bug, scenedit
