### ISSUE TITLE
Item Info fields empty in Blinlock Foundry

### ISSUE THREAD

**Issue by clort81** [calref/cboe#212] opened 2020-01-04 10:30 UTC
![iteminfomissing](https://user-images.githubusercontent.com/51511737/71764226-49470100-2ee5-11ea-8070-0033d673e081.png)

Several Item Info fields seem to be missing from all weapons in Blinlock Foundry.  Save file outside of town is attached.
[clortsave02_foundry_items.zip](https://github.com/calref/cboe/files/4021780/clortsave02_foundry_items.zip)

Damage and Bonus are visible in original game (windows)
![iteminfoorig](https://user-images.githubusercontent.com/51511737/71764371-51a03b80-2ee7-11ea-9ae2-18178ccc6609.png)

**Comment by x-qq** [comment] 2020-02-11 11:35
This is a duplicate of #65 and is fixed in 02d98db391e111569e0f9f68d297880ac50b767a

**Closed** 2020-02-11 13:16 UTC
Labels: bug, duplicate, game
