### ISSUE TITLE
Abort game -> load game -> Loading Blades of Exile save file failed.

### ISSUE THREAD

**Issue by jeremeriluoto** [calref/cboe#201] opened 2019-12-29 18:10 UTC
When starting a new game or loading a game and aborting back to main menu doesn't let you load your game any more. Only error message is displayed: "Loading Blades of Exile save file failed.". You have to restart the game to be able to load again.

**Comment by x-qq** [comment] 2020-02-07 02:03
Cannot reproduce on current master on linux.

**Comment by CelticMinstrel** [comment] 2020-02-10 05:36
I'm not sure about this exact case, but there are definitely still some circumstances where a "loading save failed" or "loading scenario failed" message is nonsensically displayed. Some relate to cancelling things.

**Comment by wrldwzrd89** [comment] 2020-02-10 10:48
In my own games I've run into similar issues. The fix was always the same: Handle NO_CHOSEN differently from DIALOG_CLOSED or CANCEL_CHOSEN.

**Comment by NQNStudios** [comment] 2024-06-24 23:43
If the OP was running on Windows, I wonder if this could be the same error as #368

**Comment by NQNStudios** [comment] 2024-07-01 21:18
I can't reproduce this on Mac or Windows. @CelticMinstrel maybe we can close it?

**Closed** 2024-07-02 04:21 UTC
Labels: bug
