### ISSUE TITLE
OSX: Action buttons during gameplay (cast mage/priest, use, combat, etc.) aren't clickable

### ISSUE THREAD

**Issue by wrldwzrd89** [calref/cboe#50] opened 2017-01-29 18:44 UTC
The keyboard shortcuts to invoke the actions for the buttons below the main map still work normally. Trying to click the buttons on macOS Sierra 10.12.3, however, does nothing. I've attached an image of the buttons in question.
<img width="284" alt="buttons" src="https://cloud.githubusercontent.com/assets/7102537/22406859/0a0f7d4e-e629-11e6-8647-c3a7120efe7f.png">

**Comment by CelticMinstrel** [comment] 2017-01-29 21:09
I've seen a few reports of issues with the action buttons, and some also saying the keyboard shortcuts don't work (the fact that they do work for you is actually quite surprising). Unfortunately, I have been unable to reproduce the issue on either of my development systems, and have no concrete theories as to the cause of the issue, so I don't think I will be able to fix it. Patches are welcome, though.

I'm marking this as affecting both Windows and OSX since I believe some of the reports were from people using the Windows build.

**Comment by CelticMinstrel** [comment] 2017-02-07 00:28
I'm wondering if this may depend on the display mode setting in the preferences dialog? It may be a long shot, but if the issue is related to wrongly correcting for different possible positionings of the UI elements in the window, it shouldn't be hard to fix.

**Comment by CelticMinstrel** [comment] 2017-02-08 16:03
My guess seems to have been right.

**Closed by CelticMinstrel** 2017-02-08 16:03 UTC
Labels: bug, osx, windows
